### ISSUE TITLE
Not working with webpack 4

### ISSUE THREAD

**Issue by ixrock** [oklas/intl-webpack-plugin#4]
package.json
```
    "webpack": "^4.5.0",
    "webpack-cli": "^2.0.14",
```

webpack config:
```
module: {
 rules: [
        {
          test: /\.ya?ml$/,
          use: [
            IntlPlugin.loader(),
            "yaml-loader"
          ]
        },
 ],
plugins: [
      new IntlPlugin({
        search: ['./client/**/*.yml']
      }),
 ]
}
```

Error:
```
[0] /Users/ixrock/Desktop/Projects/my-project/node_modules/join-webpack-plugin/node_modules/async/dist/async.js:1055
[0]         iteratee(coll[index], index, onlyOnce(iteratorCallback));
[0]         ^
[0] TypeError: Cannot read property 'slice' of undefined
[0]     at /Users/ixrock/Desktop/Projects/my-project/node_modules/join-webpack-plugin/index.js:124:37
[0]     at /Users/ixrock/Desktop/Projects/my-project/node_modules/join-webpack-plugin/node_modules/async/dist/async.js:3096:16
[0]     at eachOfArrayLike (/Users/ixrock/Desktop/Projects/my-project/node_modules/join-webpack-plugin/node_modules/async/dist/async.js:1055:9)
[0]     at eachOf (/Users/ixrock/Desktop/Projects/my-project/node_modules/join-webpack-plugin/node_modules/async/dist/async.js:1103:5)
[0]     at Object.eachLimit (/Users/ixrock/Desktop/Projects/my-project/node_modules/join-webpack-plugin/node_modules/async/dist/async.js:3158:5)
[0]     at /Users/ixrock/Desktop/Projects/my-project/node_modules/join-webpack-plugin/index.js:123:13
[0]     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/ixrock/Desktop/Projects/my-project/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:7:1)
[0]     at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/ixrock/Desktop/Projects/my-project/node_modules/tapable/lib/Hook.js:35:21)
[0]     at Compilation.seal (/Users/ixrock/Desktop/Projects/my-project/node_modules/webpack/lib/Compilation.js:896:27)
[0]     at hooks.make.callAsync.err (/Users/ixrock/Desktop/Projects/my-project/node_modules/webpack/lib/Compiler.js:479:17)
[0] npm ERR! code ELIFECYCLE
```

**Comment by ixrock** [comment]
And btw, would be good to specify plugin only in `plugins` section of webpack's config. 
Why do we need loaders section as well?

Something like this:
```
      new IntlPlugin({
        search: ['./client/**/*.yml'],
        output: {
          path: "./build/locales",
          name(filename) {
            var [name, ext] = filename.split("."); // e.g for "en.yml"
            return name + ".json"
          },
          process(content){
            // for custom merging
          }
        }
      }),
```

**Comment by oklas** [comment]
That was be very good at least some days before when I had free time. But now I'm too busy. I will inspect what is the things take place with plugin with webpack v4 some later. Take a look into join-webpack-plugin for custom merging. Loader is required because files is actually loaded by webpack via `require` function or `import` statement or it is done automatically if matched rules in `search` option. It is significant for manifest building in common build process and hot reloading.

**Comment by oklas** [comment]
Please create separated issue for your second message especially if you mean to use that bypass the webpack. It is actually different issues and may be discussed and will be solved separately. Thank you.
